### ISSUE TITLE
总共做了1次微调+1次偏好学习？

### ISSUE THREAD

**Issue by xilinniao123** [zake7749/Kyara#1]
感谢大佬分享！
总结一下您的文章：
总共做了1此微调+1次Preference learning，其中微调数据包含3个部分：base dataset+Math dataset+ rag dataset 
我的理解是否有误？

**Comment by zake7749** [comment]
我可能描述的不夠精確，實際上模型的調整總共進行了 3 次，分別有兩次的 fine-tune 以及一次的 alignment：

1. stage-1 fine-tune: 訓練在整個 [Base Dataset](https://github.com/zake7749/Kyara?tab=readme-ov-file#base-dataset-knowledge-injection-with-retrieval-augmentation) 上，Base Dataset 本身包含了 Math Dataset 與 RAG dataset 等多種 NLP 相關任務。
2. stage-2 fine-tune: 訓練在 [High Quality Dataset](https://github.com/zake7749/Kyara?tab=readme-ov-file#high-quality-dataset-model-refinement) 上。
3. Preference Learning: 基於 LLM Judge 產出的對比資料，進行 DPO 訓練。

**Comment by xilinniao123** [comment]
第2次是加载第1次训练好的模型？然后1，2次微调有何差别？--比如学习率之类的

**Comment by zake7749** [comment]
> 第2次是加载第1次训练好的模型？

正確

> 然后1，2次微调有何差别？--比如学习率之类的

二次微調本質是退火，資料面品質較高，平均的對話輪次與長度也較長。
stage-1 LR 是 2e-5，stage-2 LR 是 9e-6，除此之外，沒有什麼明顯差異。
