### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by choukevin873** [zake7749/Kyara#3]
请问模型的 license 为何？是否可供商业使用？

**Comment by zake7749** [comment]
目前 `Kyara-2b-it` 的授權遵循 [Gemma Terms of Use](https://ai.google.dev/gemma/terms)，只要符合限定條件，這個模型應當是可商用的。

不過，現在實驗仍在進行中，之後釋出的模型未必總是會採用同樣授權，屆時請再從 Huggingface 的模型頁面確認。
